Added an check around the 'M_register_gateway' function call, is no longer part of Membership 3.5.
Fatal error: Call to undefined function M_register_gateway()